language: node_js

node_js:
  - node
  - 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5

cache:
  yarn: false # true
  # directories:
  #   - .npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --ignore-scripts --ignore-engines

script:
  - yarn run lint
  - yarn run build
  - yarn run test
