language: node_js

node_js:
  - node
  - 10

cache:
  yarn: false # true
  # directories:
  #   - .npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --ignore-scripts --ignore-engines

script:
  - yarn workspace typeorm run compile
  - yarn run lint
  - yarn run build
  - yarn run test
